### ISSUE TITLE
Where are you getting the co-ords from?

### ISSUE THREAD

**Issue by Sarkie** [two10degrees/Two10.CountryLookup#5]
Where is this file from?

https://github.com/two10degrees/Two10.CountryLookup/blob/master/Two10.CountryLookup/region-list.json

It seems to be wrong near Kuwait, UAE, Iraq, Iran areas.

Thanks

**Comment by richorama** [comment]
it comes from here: https://github.com/totemstech/country-reverse-geocoding/blob/master/lib/country_reverse_geocoding.js

Happy to consider a more accurate dataset if you have one...

**Comment by Sarkie** [comment]
Do you own that dataset? Shouldn't you reference you are using it?

**Comment by richorama** [comment]
I don't own the data set, it's open source, and the license doesn't require attribution.
